# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.6.3

EAPI=8

CRATES="
	aho-corasick@0.7.19
	atty@0.2.14
	autocfg@1.1.0
	base64@0.13.0
	bitflags@1.3.2
	bstr@0.2.17
	bumpalo@3.11.0
	cast@0.3.0
	cc@1.0.73
	cfg-if@1.0.0
	clap@2.34.0
	criterion-plot@0.4.5
	criterion@0.3.6
	crossbeam-channel@0.5.6
	crossbeam-deque@0.8.2
	crossbeam-epoch@0.9.11
	crossbeam-utils@0.8.12
	csv-core@0.1.10
	csv@1.1.6
	either@1.8.0
	env_logger@0.9.1
	half@1.8.2
	hermit-abi@0.1.19
	humantime@2.1.0
	itertools@0.10.5
	itoa@0.4.8
	itoa@1.0.4
	js-sys@0.3.60
	lazy_static@1.4.0
	libc@0.2.135
	log@0.4.17
	memchr@2.5.0
	memoffset@0.6.5
	num-traits@0.2.15
	num_cpus@1.13.1
	once_cell@1.15.0
	oorandom@11.1.3
	plotters-backend@0.3.4
	plotters-svg@0.3.3
	plotters@0.3.4
	proc-macro2@1.0.47
	quote@1.0.21
	rayon-core@1.9.3
	rayon@1.5.3
	regex-automata@0.1.10
	regex-syntax@0.6.27
	regex@1.6.0
	ring@0.16.20
	rustls-pemfile@1.0.1
	rustversion@1.0.9
	ryu@1.0.11
	same-file@1.0.6
	scopeguard@1.1.0
	sct@0.7.0
	serde@1.0.145
	serde_cbor@0.11.2
	serde_derive@1.0.145
	serde_json@1.0.86
	spin@0.5.2
	syn@1.0.102
	termcolor@1.1.3
	textwrap@0.11.0
	tinytemplate@1.2.1
	unicode-ident@1.0.5
	unicode-width@0.1.10
	untrusted@0.7.1
	walkdir@2.3.2
	wasm-bindgen-backend@0.2.83
	wasm-bindgen-macro-support@0.2.83
	wasm-bindgen-macro@0.2.83
	wasm-bindgen-shared@0.2.83
	wasm-bindgen@0.2.83
	web-sys@0.3.60
	webpki-roots@0.22.5
	webpki@0.22.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
"

inherit cargo

DESCRIPTION="Rustls is a modern TLS library written in Rust."
HOMEPAGE="https://github.com/rustls/rustls"
SRC_URI="
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 ISC MIT )"
# Dependent crate licenses
LICENSE+="
	ISC MIT MPL-2.0 Unicode-DFS-2016
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
