# Copyright 2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.6.3

EAPI=8

CRATES="
	autocfg@1.1.0
	bitflags@1.3.2
	cfg-if@1.0.0
	crossbeam-channel@0.5.4
	crossbeam-utils@0.8.8
	filetime@0.2.16
	fsevent-sys@4.1.0
	indoc@1.0.4
	inotify-sys@0.1.5
	inotify@0.9.6
	kqueue-sys@1.0.3
	kqueue@1.0.5
	lazy_static@1.4.0
	libc@0.2.124
	lock_api@0.4.7
	log@0.4.16
	memoffset@0.6.5
	mio@0.8.2
	miow@0.3.7
	notify@5.0.0
	ntapi@0.3.7
	once_cell@1.10.0
	parking_lot@0.12.0
	parking_lot_core@0.9.2
	proc-macro2@1.0.37
	pyo3-build-config@0.17.3
	pyo3-ffi@0.17.3
	pyo3-macros-backend@0.17.3
	pyo3-macros@0.17.3
	pyo3@0.17.3
	quote@1.0.18
	redox_syscall@0.2.13
	same-file@1.0.6
	scopeguard@1.1.0
	smallvec@1.8.0
	syn@1.0.91
	target-lexicon@0.12.3
	unicode-xid@0.2.2
	unindent@0.1.8
	walkdir@2.3.2
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.34.0
	windows_aarch64_msvc@0.34.0
	windows_i686_gnu@0.34.0
	windows_i686_msvc@0.34.0
	windows_x86_64_gnu@0.34.0
	windows_x86_64_msvc@0.34.0
"

inherit cargo

DESCRIPTION=""
HOMEPAGE="https://github.com/samuelcolvin/watchfiles/watchfiles"
SRC_URI="
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions ISC MIT
	|| ( Artistic-2 CC0-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
